export default [
  { id: 1, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 2, img: "/img/projects/house.jpg", type: "house" },
  { id: 3, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 4, img: "/img/projects/house.jpg", type: "house" },
  { id: 5, img: "/img/projects/house.jpg", type: "house" },
  { id: 6, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 7, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 8, img: "/img/projects/house.jpg", type: "house" },
  { id: 9, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 10, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 11, img: "/img/projects/house.jpg", type: "house" },
  { id: 12, img: "/img/projects/house.jpg", type: "house" },
  { id: 13, img: "/img/projects/house.jpg", type: "house" },
  { id: 14, img: "/img/projects/house.jpg", type: "house" },
  { id: 15, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 16, img: "/img/projects/house.jpg", type: "house" },
  { id: 17, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 18, img: "/img/projects/house.jpg", type: "house" },
  { id: 19, img: "/img/projects/house.jpg", type: "house" },
  { id: 20, img: "/img/projects/house.jpg", type: "house" },
  { id: 21, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 22, img: "/img/projects/yacht.jpg", type: "yacht" },
  { id: 23, img: "/img/projects/yacht.jpg", type: "yacht" },
];
